name: HowToWorkWith-test
on: [push]
jobs:
  HowToWorkWith-test:
    runs-on: ubuntu-20.04
    steps:
      - run:
          echo *** LOAD ***
          sudo mkdir -p /hom/HowToWorkWith/
          sudo git clone https://github.com/ESJW/sk_summer_test.git /home/HowToWorkWith/
          cd /home/HowToWorkWith/
          echo *** LOAD ***
          
          echo *** INSTALL ***
          sudo apt-get update
          sudo apt install python3-pip
          
          sudo apt install python3-pytest
          
          echo *** INSTALL ***
          
          echo *** TEST ***
          pytest-3 test_bench.py --disable-warnings
          echo *** TEST ***
